### PR TITLE
feat: node 4.x compatibility

### PR DESCRIPTION
**Pull request by tamascsaba**
P.R for: https://github.com/hhsnopek/code-frame/issues/2 issue

### CODE REVIEW

**Comment by hhsnopek** [comment]
Could you add `4` to the `.travis.yml`? Then we'll have tests for both node 6 & 4 😄

**Comment by tamascsaba** [comment]
Yes. of course, I added :)

**Comment by tamascsaba** [comment]
Travis passed, pls change version and release to npm :), thx.

**Comment by hhsnopek** [comment]
published! https://github.com/hhsnopek/code-frame/releases/tag/v2.0.0

**Pull request merged**
